# Generated by Django 2.2.1 on 2019-08-06 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarComponentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=16, unique=True)),
                ('component_name', models.CharField(max_length=32)),
                ('manufacture', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('func_param', models.CharField(max_length=64)),
                ('remark', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'car_components_info',
            },
        ),
        migrations.CreateModel(
            name='CarsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=32, unique=True)),
                ('car_name', models.CharField(max_length=64)),
                ('produce_time', models.DateField()),
                ('car_weight', models.IntegerField()),
                ('allowable_weight', models.IntegerField()),
                ('power', models.IntegerField()),
                ('engine', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
                ('color_list', models.CharField(max_length=8)),
                ('remark', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cars_info',
            },
        ),
        migrations.CreateModel(
            name='CustomersInfo',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=16)),
                ('telephone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=1)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'customers_info',
            },
        ),
        migrations.CreateModel(
            name='EmployeesInfo',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(max_length=18, unique=True)),
                ('emp_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=16)),
                ('is_admin', models.CharField(default='F', max_length=1)),
                ('telephone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=1)),
                ('join_time', models.DateField()),
                ('emp_dept', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'employees_info',
            },
        ),
        migrations.CreateModel(
            name='ErrorsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_code', models.CharField(max_length=32, unique=True)),
                ('err_desc', models.CharField(max_length=256)),
                ('remark', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'errors_info',
            },
        ),
        migrations.CreateModel(
            name='UserCarsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=1)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CA_Demo.CarsInfo', verbose_name='car_id')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CA_Demo.CustomersInfo', verbose_name='car_owner_id')),
            ],
            options={
                'db_table': 'user_cars_info',
            },
        ),
        migrations.CreateModel(
            name='RepairInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_desc', models.CharField(max_length=128)),
                ('repair_time', models.DateTimeField(auto_now=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CA_Demo.CarsInfo', verbose_name='repair_car_id')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CA_Demo.CustomersInfo', verbose_name='repair_cus_id')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CA_Demo.EmployeesInfo', verbose_name='repair_emp_id')),
            ],
            options={
                'db_table': 'repair_info',
            },
        ),
    ]
