# Generated by Django 2.2.1 on 2019-08-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarComponentsInfo',
            fields=[
                ('component_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='部件编号')),
                ('component_name', models.CharField(max_length=32, verbose_name='部件名称')),
                ('manufacture', models.CharField(max_length=64, verbose_name='生产厂商')),
                ('price', models.FloatField(verbose_name='单价')),
                ('func_param', models.CharField(max_length=64, verbose_name='性能参数')),
                ('is_removed', models.CharField(default='F', max_length=1, verbose_name='是否还在生产')),
                ('remark', models.CharField(max_length=128, verbose_name='备注')),
            ],
            options={
                'verbose_name': '车辆部件信息',
                'verbose_name_plural': '车辆部件信息',
                'db_table': 'car_components_info',
            },
        ),
        migrations.CreateModel(
            name='CarsInfo',
            fields=[
                ('car_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='车辆型号')),
                ('car_name', models.CharField(max_length=64, verbose_name='车辆名称')),
                ('produce_time', models.DateField(verbose_name='出厂时间')),
                ('car_weight', models.IntegerField(verbose_name='总质量(kg)')),
                ('allowable_weight', models.IntegerField(verbose_name='额定承重量(kg)')),
                ('power', models.IntegerField(verbose_name='电机功率(kw)')),
                ('engine', models.CharField(max_length=32, verbose_name='发动机型号')),
                ('number', models.IntegerField(verbose_name='乘员数')),
                ('color_list', models.CharField(max_length=8, verbose_name='色系')),
                ('is_removed', models.CharField(default='F', max_length=1, verbose_name='生产状态')),
                ('remark', models.CharField(max_length=128, verbose_name='备注')),
            ],
            options={
                'verbose_name': '车辆信息',
                'verbose_name_plural': '车辆信息',
                'db_table': 'cars_info',
            },
        ),
        migrations.CreateModel(
            name='CustomersInfo',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('cus_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('telephone', models.CharField(max_length=16, verbose_name='联系方式')),
                ('email', models.CharField(max_length=32, verbose_name='邮件')),
                ('sex', models.CharField(max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
                'db_table': 'customers_info',
            },
        ),
        migrations.CreateModel(
            name='EmployeesInfo',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('emp_id', models.CharField(max_length=18, unique=True, verbose_name='员工编号')),
                ('emp_name', models.CharField(max_length=64, verbose_name='员工姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('is_admin', models.CharField(default='F', max_length=1, verbose_name='是否为管理员')),
                ('telephone', models.CharField(max_length=16, verbose_name='联系方式')),
                ('email', models.CharField(max_length=32, verbose_name='邮件')),
                ('sex', models.CharField(max_length=1, verbose_name='性别')),
                ('join_time', models.DateField(verbose_name='入职时间')),
                ('emp_dept', models.CharField(max_length=4, verbose_name='所在部门')),
                ('is_removed', models.CharField(default='F', max_length=1, verbose_name='是否在职')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 'employees_info',
            },
        ),
        migrations.CreateModel(
            name='ErrorsInfo',
            fields=[
                ('err_code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='故障代码')),
                ('err_desc', models.CharField(max_length=256, verbose_name='故障描述')),
                ('remark', models.CharField(max_length=128, verbose_name='修复建议')),
            ],
            options={
                'verbose_name': '故障信息',
                'verbose_name_plural': '故障信息',
                'db_table': 'errors_info',
            },
        ),
        migrations.CreateModel(
            name='UserCarsInfo',
            fields=[
                ('plate_number', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='车牌号')),
                ('color', models.CharField(max_length=1, verbose_name='车身颜色')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CA_Demo.CarsInfo', verbose_name='车辆型号')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CA_Demo.CustomersInfo', verbose_name='车主姓名')),
            ],
            options={
                'verbose_name': '用户-车辆信息',
                'verbose_name_plural': '用户-车辆信息',
                'db_table': 'user_cars_info',
            },
        ),
        migrations.CreateModel(
            name='RepairInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=8, verbose_name='车牌号')),
                ('repair_desc', models.CharField(max_length=128, verbose_name='故障描述')),
                ('repair_time', models.DateTimeField(auto_now=True, verbose_name='维修时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CA_Demo.CustomersInfo', verbose_name='客户姓名')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CA_Demo.EmployeesInfo', verbose_name='维修人员')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
                'db_table': 'repair_info',
            },
        ),
    ]
