# Generated by Django 2.2.1 on 2019-08-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA_Demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcomponentsinfo',
            name='is_removed',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='carsinfo',
            name='is_removed',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='employeesinfo',
            name='is_removed',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
