# Generated by Django 2.2.1 on 2019-08-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA_Demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcomponentsinfo',
            name='component_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='部件编号'),
        ),
        migrations.AlterField(
            model_name='carsinfo',
            name='car_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='车辆型号'),
        ),
        migrations.AlterField(
            model_name='errorsinfo',
            name='err_code',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='故障代码'),
        ),
    ]
