# Generated by Django 2.2.1 on 2019-08-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA_Demo', '0002_auto_20190806_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersinfo',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='employeesinfo',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
